on:
  release:
    types: [created]

name: Upload Release Asset (macOS)

jobs:
  build:
    name: Run Tests
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete npm prefix
        run: npm config delete prefix

      - name: Install dependencies
        shell: bash --login {0}
        run: nvm install 14 && nvm use 14

      - name: Build project
        shell: bash --login {0}
        run: |
          npm install --ignore-scripts
          npm run install:source
          ls -la ./build/src/bindings/ejdb2_node/ejdb2_node/

      - name: Run tests
        run: npm run test

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./build/src/bindings/ejdb2_node/darwin-x64/ejdb2_node.node
          asset_name: ejdb2_node_x64_darwin_x64.node
          asset_content_type: application/octet-stream
