on:
  pull_request:

name: Run Tests

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [linux-node14, alpine-node14]
        include:
          - type: linux-node14
            image: node:14
            node-version: 14.x
            os: linux
            run: |
              apt-get update
              apt-get install -y cmake make gcc git

          - type: alpine-node14
            image: node:14-alpine
            node-version: 14.x
            os: alpine
            run: |
              apk update
              apk add cmake make g++ git

    container:
      image: ${{ matrix.image }}
    steps:
      - name: Build project
        run: ${{ matrix.run }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install
        run: |
          npm install --ignore-scripts
          npm run install:source

      - name: Run tests
        run: npm run test
