on:
  pull_request:

name: Run Tests

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [linux-node16, alpine-node16]
        include:
          - type: linux-node16
            image: node:16
            node-version: 16.x
            os: linux
            run: |
              apt-get update
              apt-get install -y make gcc git
              wget -O /cmake-Linux-x86_64.sh https://github.com/Kitware/CMake/releases/download/v3.23.0-rc3/cmake-3.23.0-rc3-linux-x86_64.sh
              mkdir /opt/cmake
              sh /cmake-Linux-x86_64.sh --prefix=/opt/cmake --skip-license
              ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake

          - type: alpine-node16
            image: node:16-alpine
            node-version: 16.x
            os: alpine
            run: |
              apk update
              apk add cmake make g++ git

    container:
      image: ${{ matrix.image }}
    steps:
      - name: Build project
        run: ${{ matrix.run }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install
        run: |
          npm install --ignore-scripts
          npm run install:source

      - name: Run tests
        run: npm run test
